# Streamlit Secrets Configuration Template
# Create this file as .streamlit/secrets.toml in your project directory

[database]
# Option 1: SQL Server on Campus Network (Windows Authentication)
connection_string = "Driver={ODBC Driver 17 for SQL Server};Server=your-sql-server-name;Database=Inspections;Trusted_Connection=yes;"

# Option 2: Azure SQL Database
# connection_string = "Driver={ODBC Driver 17 for SQL Server};Server=tcp:yourserver.database.windows.net,1433;Database=Inspections;Uid=yourusername;Pwd=yourpassword;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"

[api]
gemini_api_key = "AIzaSyCxo29Q6HRHRzxTuTU_IanG9yvJmctdzb0"
power_automate_url = "https://defaultec37a091b9a647e598d0903d4a4192.03.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/da9ca2f832b44a5fb19f50d0462068b3/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=-sb1eRCUppSwjFPD_zX02_25KpU78k4QIbZwjDffrQU"